name: Gilded Sentinel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore gilded-sentinel-client.csproj

      - name: Build in Release mode for Windows
        run: dotnet build gilded-sentinel-client.csproj --configuration Release --runtime win-x64

      - name: Publish for Windows x64
        run: dotnet publish gilded-sentinel-client.csproj --configuration Release --runtime win-x64 --output ./assemblies/win-x64

      - name: Create ZIP file for Windows
        run: |
          mkdir -p ./assemblies/win-x64/zipped
          cd ./assemblies/win-x64
          zip -r gilded-sentinel-client-${{ github.run_number }}.zip gilded-sentinel-client.exe appsettings.json

      - name: Upload Windows Build ZIP
        uses: actions/upload-artifact@v4
        with:
          name: Gilded-Sentinel-Build-Win-x64-${{ github.sha }}
          path: ./assemblies/win-x64/gilded-sentinel-client-${{ github.run_number }}.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore gilded-sentinel-client.csproj

      - name: Build in Release mode for Linux
        run: dotnet build gilded-sentinel-client.csproj --configuration Release --runtime linux-x64

      - name: Publish for Linux x64
        run: dotnet publish gilded-sentinel-client.csproj --configuration Release --runtime linux-x64 --output ./assemblies/linux-x64

      - name: Create ZIP file for Linux
        run: |
          mkdir -p ./assemblies/linux-x64/zipped
          cd ./assemblies/linux-x64
          zip -r gilded-sentinel-client-${{ github.run_number }}.zip gilded-sentinel-client appsettings.json

      - name: Upload Linux Build ZIP
        uses: actions/upload-artifact@v4
        with:
          name: Gilded-Sentinel-Build-Linux-x64-${{ github.sha }}
          path: ./assemblies/linux-x64/gilded-sentinel-client-${{ github.run_number }}.zip

  create-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Windows Build ZIP
        uses: actions/download-artifact@v4
        with:
          name: Gilded-Sentinel-Build-Win-x64-${{ github.sha }}
          path: ./assemblies/win-x64

      - name: Download Linux Build ZIP
        uses: actions/download-artifact@v4
        with:
          name: Gilded-Sentinel-Build-Linux-x64-${{ github.sha }}
          path: ./assemblies/linux-x64

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create Git Tag
        id: tag
        run: |
          git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
          git push origin "v${{ github.run_number }}"

      - name: Verify Tag Creation
        run: git tag -l

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./assemblies/win-x64/gilded-sentinel-client-${{ github.run_number }}.zip
            ./assemblies/linux-x64/gilded-sentinel-client-${{ github.run_number }}.zip
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
